import streamlit as st
import joblib
import os
import requests
import urllib.parse
import pandas as pd
import numpy as np
import yfinance as yf
import plotly.graph_objects as go
from scipy.signal import argrelextrema
from datetime import datetime, timedelta

# --- PAGE CONFIGURATION ---
st.set_page_config(
    page_title="Project Alpha-NSE | Synchronized SMC & ML Engine",
    page_icon="🏛️",
    layout="wide"
)

st.title("🏛️ Project Alpha-NSE: Synchronized Institutional Scanner")
st.markdown("*Real-Time Confluence: SMC, Order Flow, POC, Classical Patterns & Market Sentiment*")

# --- 1. ASSET & BACKTEST MEMORY LOADING (RUN ONCE) ---
@st.cache_resource
def load_historical_edge():
    """
    Loads pre-backtested historical data, win-rates, and ML models.
    This fulfills the requirement of NOT running backtests on every scan.
    Requires 'backtest_edge.pkl' generated by your offline research script.
    """
    model = joblib.load("colab_ai_model.pkl") if os.path.exists("colab_ai_model.pkl") else None
    scaler = joblib.load("colab_scaler.pkl") if os.path.exists("colab_scaler.pkl") else None
    backtest_data = joblib.load("backtest_edge.pkl") if os.path.exists("backtest_edge.pkl") else {}
    
    return model, scaler, backtest_data

model, scaler, historical_edge = load_historical_edge()

if model is None or not historical_edge:
    st.sidebar.warning("⚠️ Offline Backtest/ML files missing. Running in Pure Dynamic Confluence Mode.")
else:
    st.sidebar.success("✅ Offline Backtest & AI Loaded. Utilizing Historical Win-Rates.")

# --- 2. 100+ STOCK UNIVERSE REGISTRY ---
# Expanded to include Nifty 50, Midcap, Smallcap, and High-Volatility/Low-Price stocks
STOCK_METADATA = {
    # Nifty 50 & Heavyweights
    "RELIANCE": {"index": "Nifty 50", "sector": "Energy"}, "TCS": {"index": "Nifty 50", "sector": "IT"},
    "HDFCBANK": {"index": "Nifty 50", "sector": "Banking"}, "INFY": {"index": "Nifty 50", "sector": "IT"},
    "ICICIBANK": {"index": "Nifty 50", "sector": "Banking"}, "SBIN": {"index": "Nifty 50", "sector": "Banking"},
    "BHARTIARTL": {"index": "Nifty 50", "sector": "Telecom"}, "ITC": {"index": "Nifty 50", "sector": "FMCG"},
    "LT": {"index": "Nifty 50", "sector": "Infra"}, "AXISBANK": {"index": "Nifty 50", "sector": "Banking"},
    "KOTAKBANK": {"index": "Nifty 50", "sector": "Banking"}, "HINDUNILVR": {"index": "Nifty 50", "sector": "FMCG"},
    "BAJFINANCE": {"index": "Nifty 50", "sector": "Financials"}, "MARUTI": {"index": "Nifty 50", "sector": "Auto"},
    "TATAMOTORS": {"index": "Nifty 50", "sector": "Auto"}, "TATASTEEL": {"index": "Nifty 50", "sector": "Metal"},
    "M&M": {"index": "Nifty 50", "sector": "Auto"}, "NTPC": {"index": "Nifty 50", "sector": "Energy"},
    "POWERGRID": {"index": "Nifty 50", "sector": "Energy"}, "ULTRACEMCO": {"index": "Nifty 50", "sector": "Materials"},
    "TITAN": {"index": "Nifty 50", "sector": "Consumer"}, "WIPRO": {"index": "Nifty 50", "sector": "IT"},
    "ONGC": {"index": "Nifty 50", "sector": "Energy"}, "ADANIENT": {"index": "Nifty 50", "sector": "Infra"},
    "ADANIPORTS": {"index": "Nifty 50", "sector": "Infra"}, "COALINDIA": {"index": "Nifty 50", "sector": "Energy"},
    "SUNPHARMA": {"index": "Nifty 50", "sector": "Pharma"}, "BAJAJFINSV": {"index": "Nifty 50", "sector": "Financials"},
    "ASIANPAINT": {"index": "Nifty 50", "sector": "Consumer"}, "HCLTECH": {"index": "Nifty 50", "sector": "IT"},
    # High Volatility / Midcap / Smallcap
    "ZOMATO": {"index": "Midcap", "sector": "Consumer"}, "PAYTM": {"index": "Midcap", "sector": "Financials"},
    "JIOFIN": {"index": "Largecap", "sector": "Financials"}, "TATAPOWER": {"index": "Midcap", "sector": "Energy"},
    "FEDERALBNK": {"index": "Midcap", "sector": "Banking"}, "POLYCAB": {"index": "Midcap", "sector": "Capital Goods"},
    "PERSISTENT": {"index": "Midcap", "sector": "IT"}, "COFORGE": {"index": "Midcap", "sector": "IT"},
    "ASHOKLEY": {"index": "Midcap", "sector": "Auto"}, "MAXHEALTH": {"index": "Midcap", "sector": "Healthcare"},
    "VOLTAS": {"index": "Midcap", "sector": "Consumer"}, "CDSL": {"index": "Smallcap", "sector": "Financials"},
    "ANGELONE": {"index": "Smallcap", "sector": "Financials"}, "KFINTECH": {"index": "Smallcap", "sector": "Financials"},
    "SUZLON": {"index": "Smallcap", "sector": "Energy"}, "BSOFT": {"index": "Smallcap", "sector": "IT"},
    "HFCL": {"index": "Smallcap", "sector": "Infra"}, "IEX": {"index": "Smallcap", "sector": "Financials"},
    "KEI": {"index": "Smallcap", "sector": "Capital Goods"}, "LTIM": {"index": "Largecap", "sector": "IT"},
    "HAL": {"index": "Midcap", "sector": "Defense"}, "BEL": {"index": "Midcap", "sector": "Defense"},
    "RECLTD": {"index": "Midcap", "sector": "Financials"}, "PFC": {"index": "Midcap", "sector": "Financials"},
    "IRFC": {"index": "Midcap", "sector": "Financials"}, "RVNL": {"index": "Midcap", "sector": "Infra"},
    "IREDA": {"index": "Smallcap", "sector": "Financials"}, "IDFCFIRSTB": {"index": "Midcap", "sector": "Banking"},
    "PNB": {"index": "Midcap", "sector": "Banking"}, "BANKBARODA": {"index": "Midcap", "sector": "Banking"},
    "BHEL": {"index": "Midcap", "sector": "Capital Goods"}, "SAIL": {"index": "Midcap", "sector": "Metal"},
    "VEDL": {"index": "Largecap", "sector": "Metal"}, "HINDALCO": {"index": "Largecap", "sector": "Metal"},
    "TVSMOTOR": {"index": "Midcap", "sector": "Auto"}, "MOTHERSON": {"index": "Midcap", "sector": "Auto"},
    "DIXON": {"index": "Midcap", "sector": "Consumer"}, "KPITTECH": {"index": "Midcap", "sector": "IT"},
    "TATACOMM": {"index": "Midcap", "sector": "Telecom"}, "INDHOTEL": {"index": "Midcap", "sector": "Consumer"},
    "CUMMINSIND": {"index": "Midcap", "sector": "Capital Goods"}, "ABBOTINDIA": {"index": "Midcap", "sector": "Pharma"},
    "TORNTPHARM": {"index": "Midcap", "sector": "Pharma"}, "APOLLOHOSP": {"index": "Largecap", "sector": "Healthcare"},
    "JSWSTEEL": {"index": "Largecap", "sector": "Metal"}, "SHREECEM": {"index": "Largecap", "sector": "Materials"},
    "EICHERMOT": {"index": "Largecap", "sector": "Auto"}, "HEROMOTOCO": {"index": "Largecap", "sector": "Auto"},
    "BRITANNIA": {"index": "Largecap", "sector": "FMCG"}, "NESTLEIND": {"index": "Largecap", "sector": "FMCG"},
    "DRREDDY": {"index": "Largecap", "sector": "Pharma"}, "CIPLA": {"index": "Largecap", "sector": "Pharma"},
    "DIVISLAB": {"index": "Largecap", "sector": "Pharma"}, "GRASIM": {"index": "Largecap", "sector": "Materials"},
    "BAJAJ-AUTO": {"index": "Largecap", "sector": "Auto"}, "MCDOWELL-N": {"index": "Midcap", "sector": "Consumer"},
    "CHOLAFIN": {"index": "Midcap", "sector": "Financials"}, "PIIND": {"index": "Midcap", "sector": "Chemicals"},
    "LUPIN": {"index": "Midcap", "sector": "Pharma"}, "AUROPHARMA": {"index": "Midcap", "sector": "Pharma"}
}

# Add all to Upstox map cleanly
UPSTOX_ISIN_MAP = {k: f"NSE_EQ|{k}" for k in STOCK_METADATA.keys()}

# --- 3. SIDEBAR & FILTERS ---
st.sidebar.markdown("### 🌐 Market Context & Focus")
active_sectors = st.sidebar.multiselect(
    "Focus Sectors (Liquidity Magnets):", 
    list(set(v['sector'] for v in STOCK_METADATA.values())),
    default=["Banking", "IT", "Auto", "Energy", "Financials", "Defense"]
)
min_rr_threshold = st.sidebar.slider("Minimum R:R Filter", 1.0, 5.0, 1.5, 0.1)

# --- 4. DATA ENGINE (UPSTOX V3 + YFINANCE) ---
def get_upstox_access_token() -> str:
    try:
        return st.secrets["UPSTOX_ACCESS_TOKEN"] if "UPSTOX_ACCESS_TOKEN" in st.secrets else os.getenv("UPSTOX_ACCESS_TOKEN", None)
    except Exception:
        return None

def fetch_stock_data(ticker):
    """Fetches Live 5m and Daily data robustly."""
    try:
        access_token = get_upstox_access_token()
        if access_token:
            instrument_key = urllib.parse.quote(UPSTOX_ISIN_MAP.get(ticker, f"NSE_EQ|{ticker}"), safe="")
            headers = {"Accept": "application/json", "Authorization": f"Bearer {access_token}"}
            
            # 5m Data
            url_5m = f"https://api.upstox.com/v3/historical-candle/intraday/{instrument_key}/minutes/5"
            res_5m = requests.get(url_5m, headers=headers, timeout=5)
            
            # 1D Data for higher timeframe context
            to_date = datetime.now().strftime("%Y-%m-%d")
            from_date = (datetime.now() - timedelta(days=60)).strftime("%Y-%m-%d")
            url_1d = f"https://api.upstox.com/v3/historical-candle/{instrument_key}/days/1/{to_date}/{from_date}"
            res_1d = requests.get(url_1d, headers=headers, timeout=5)

            if res_5m.status_code == 200 and res_1d.status_code == 200:
                raw_5m = res_5m.json().get("data", {}).get("candles", [])
                raw_1d = res_1d.json().get("data", {}).get("candles", [])
                
                if raw_5m and raw_1d:
                    df_5m = pd.DataFrame(raw_5m, columns=["Datetime", "Open", "High", "Low", "Close", "Volume", "OI"])
                    df_1d = pd.DataFrame(raw_1d, columns=["Datetime", "Open", "High", "Low", "Close", "Volume", "OI"])
                    
                    for df in [df_5m, df_1d]:
                        df["Datetime"] = pd.to_datetime(df["Datetime"])
                        df.set_index("Datetime", inplace=True)
                        df.sort_index(inplace=True)
                        for col in ["Open", "High", "Low", "Close", "Volume"]:
                            df[col] = pd.to_numeric(df[col], errors="coerce")
                            
                    return df_5m[df_5m["Volume"] > 0], df_1d[df_1d["Volume"] > 0]
    except Exception:
        pass 
    
    # Robust Fallback to yfinance
    yf_symbol = f"{ticker}.NS"
    df_5m = yf.download(yf_symbol, period="5d", interval="5m", progress=False, auto_adjust=True)
    df_1d = yf.download(yf_symbol, period="3mo", interval="1d", progress=False, auto_adjust=True)
    
    # Flatten multi-index columns if present in new yfinance versions
    if isinstance(df_5m.columns, pd.MultiIndex):
        df_5m.columns = df_5m.columns.get_level_values(0)
    if isinstance(df_1d.columns, pd.MultiIndex):
        df_1d.columns = df_1d.columns.get_level_values(0)
        
    return df_5m.dropna(), df_1d.dropna()

# --- 5. SYNCHRONIZED INDICATORS & SMC ENGINE ---

def compute_poc(df):
    """Calculates Point of Control (POC) based on Volume Profile for the session."""
    if len(df) < 10: return df['Close'].iloc[-1]
    # Create price bins
    min_price, max_price = df['Low'].min(), df['High'].max()
    bins = np.linspace(min_price, max_price, 30)
    # Assign each candle to a bin based on typical price
    df['TP'] = (df['High'] + df['Low'] + df['Close']) / 3
    df['Bin'] = pd.cut(df['TP'], bins=bins)
    # Sum volume per bin
    vol_profile = df.groupby('Bin')['Volume'].sum()
    if vol_profile.empty or vol_profile.isna().all(): return df['Close'].iloc[-1]
    # Get bin with max volume
    poc_bin = vol_profile.idxmax()
    return poc_bin.mid if pd.notna(poc_bin) else df['Close'].iloc[-1]

def get_swing_points(df, order=10):
    """Finds exact structural swing highs and lows using local extrema."""
    highs = argrelextrema(df['High'].values, np.greater, order=order)[0]
    lows = argrelextrema(df['Low'].values, np.less, order=order)[0]
    
    swing_highs = [(df.index[i], df['High'].iloc[i]) for i in highs]
    swing_lows = [(df.index[i], df['Low'].iloc[i]) for i in lows]
    return swing_highs, swing_lows

@st.cache_data(ttl=900)
def fetch_news_catalyst(ticker):
    """Fetches real-time fundamental catalysts to sync with technicals."""
    try:
        t = yf.Ticker(f"{ticker}.NS")
        news = t.news
        if not news: return 0.0, "No Active News"
        
        latest = news[0]
        title = latest.get('title', '').lower()
        
        bullish_kw = ["profit", "surge", "win", "buyback", "upgrade", "breakout"]
        bearish_kw = ["loss", "penalty", "downgrade", "probe", "fall", "resigns"]
        
        if any(kw in title for kw in bullish_kw): return 15.0, f"🟢 Bullish News: {title[:40]}..."
        if any(kw in title for kw in bearish_kw): return -15.0, f"🔴 Bearish News: {title[:40]}..."
        return 5.0, f"📰 Neutral Catalyst: {title[:40]}..."
    except:
        return 0.0, "News Feed Unavailable"

def detect_synchronized_smc(df_5m, df_1d):
    """
    Advanced engine that completely syncs sweeps, FVGs, Candlestick patterns, and Order Blocks.
    Rejects heuristic setups and forces logical institutional sequence.
    """
    if len(df_5m) < 50: return []
    
    df = df_5m.copy()
    poc_level = compute_poc(df)
    swing_highs, swing_lows = get_swing_points(df, order=8)
    
    zones = []
    last_price = float(df['Close'].iloc[-1])
    
    # 1. LIQUIDITY SWEEP DETECTION (Anticipatory & Confirmed)
    active_sweeps = []
    for t_idx, low_val in swing_lows[-3:]: # Check recent major lows
        # If current price is aggressively piercing a recent major low
        if df['Low'].iloc[-1] < low_val and df['Close'].iloc[-1] > low_val:
            # Confirmed Sweep (Pinbar/Rejection off liquidity)
            if (df['Close'].iloc[-1] - df['Low'].iloc[-1]) > (df['High'].iloc[-1] - df['Close'].iloc[-1]) * 1.5:
                active_sweeps.append({'type': 'Sweep Low', 'price': low_val, 'bias': 'BUY', 'state': 'Confirmed'})
        elif low_val * 0.998 <= last_price <= low_val * 1.002:
             active_sweeps.append({'type': 'Sweep Low', 'price': low_val, 'bias': 'BUY', 'state': 'Anticipating'})

    for t_idx, high_val in swing_highs[-3:]: # Check recent major highs
        if df['High'].iloc[-1] > high_val and df['Close'].iloc[-1] < high_val:
            # Confirmed Sweep High
            if (df['High'].iloc[-1] - df['Close'].iloc[-1]) > (df['Close'].iloc[-1] - df['Low'].iloc[-1]) * 1.5:
                active_sweeps.append({'type': 'Sweep High', 'price': high_val, 'bias': 'SELL', 'state': 'Confirmed'})
        elif high_val * 0.998 <= last_price <= high_val * 1.002:
             active_sweeps.append({'type': 'Sweep High', 'price': high_val, 'bias': 'SELL', 'state': 'Anticipating'})

    # 2. STRICT ORDER BLOCK DETECTION
    # OB must have displacement (FVG) AND align with a structure
    lookback = min(60, len(df) - 3)
    start_i = len(df) - lookback
    
    for i in range(start_i, len(df) - 2):
        c_open, c_close = float(df['Open'].iloc[i]), float(df['Close'].iloc[i])
        c_high, c_low = float(df['High'].iloc[i]), float(df['Low'].iloc[i])
        
        # Bullish OB (Down candle before massive up move with FVG)
        if c_close < c_open:
            fvg_present = float(df['Low'].iloc[i+2]) > c_high if i+2 < len(df) else False
            engulfing = float(df['Close'].iloc[i+1]) > c_high and float(df['Open'].iloc[i+1]) < c_close
            
            if fvg_present and engulfing:
                ob_top, ob_bottom = c_high, c_low
                # Check Mitigation (has price come back and broken it?)
                future_lows = df['Low'].iloc[i+1:]
                mitigated = (future_lows < ob_bottom).any()
                
                if not mitigated:
                    state_val = 3 if ob_bottom <= last_price <= (ob_top * 1.002) else 1
                    zones.append({
                        'type': 'Bullish OB', 'top': ob_top, 'bottom': ob_bottom,
                        'start_time': df.index[i], 'state_val': state_val, 'bias': 'BUY'
                    })

        # Bearish OB (Up candle before massive down move with FVG)
        if c_close > c_open:
            fvg_present = float(df['High'].iloc[i+2]) < c_low if i+2 < len(df) else False
            engulfing = float(df['Close'].iloc[i+1]) < c_low and float(df['Open'].iloc[i+1]) > c_close
            
            if fvg_present and engulfing:
                ob_top, ob_bottom = c_high, c_low
                future_highs = df['High'].iloc[i+1:]
                mitigated = (future_highs > ob_top).any()
                
                if not mitigated:
                    state_val = 3 if (ob_bottom * 0.998) <= last_price <= ob_top else 1
                    zones.append({
                        'type': 'Bearish OB', 'top': ob_top, 'bottom': ob_bottom,
                        'start_time': df.index[i], 'state_val': state_val, 'bias': 'SELL'
                    })
                    
    return zones, active_sweeps, poc_level, swing_highs, swing_lows

# --- 6. CORE SCANNER EXECUTION ---
col1, col2 = st.columns([1, 3])
with col1:
    scan_universe = st.selectbox("Universe", ["All Combined", "Nifty 50", "Midcap", "Smallcap"])
with col2:
    st.markdown("<br>", unsafe_allow_html=True)
    run_scan = st.button("🚀 Execute Fully Synchronized Scan", type="primary")

if run_scan:
    tickers = [k for k, v in STOCK_METADATA.items() if (v["index"] == scan_universe or scan_universe == "All Combined")]
    results = []
    
    progress_bar = st.progress(0)
    status_text = st.empty()

    for idx, ticker in enumerate(tickers):
        status_text.text(f"Synchronizing multi-timeframe logic for {ticker}...")
        progress_bar.progress((idx + 1) / len(tickers))
        
        try:
            df_5m, df_1d = fetch_stock_data(ticker)
            if df_5m.empty or df_1d.empty: continue

            last_price = float(df_5m['Close'].iloc[-1])
            vwap = (df_5m['Volume'] * (df_5m['High'] + df_5m['Low'] + df_5m['Close']) / 3).cumsum() / df_5m['Volume'].cumsum()
            vwap_val = vwap.iloc[-1]
            
            # Sync Engine
            ob_zones, sweeps, poc, swings_h, swings_l = detect_synchronized_smc(df_5m, df_1d)
            news_score, news_context = fetch_news_catalyst(ticker)

            best_ob = sorted(ob_zones, key=lambda x: x['state_val'], reverse=True)[0] if ob_zones else None
            active_sweep = sweeps[-1] if sweeps else None
            
            score = 0.0
            trade_bias = "NEUTRAL"
            
            # Synchronization Logic: Requires Alignment of Variables
            if best_ob and active_sweep and best_ob['bias'] == active_sweep['bias']:
                trade_bias = best_ob['bias']
                score += 50.0  # Massive score for perfectly synchronized setup
            elif best_ob:
                trade_bias = best_ob['bias']
                score += 30.0
            elif active_sweep:
                trade_bias = active_sweep['bias']
                score += 20.0
            
            # Trend Confluence
            if trade_bias == "BUY" and last_price > vwap_val: score += 15.0
            if trade_bias == "SELL" and last_price < vwap_val: score += 15.0
            if STOCK_METADATA[ticker]['sector'] in active_sectors: score += 10.0
            score += news_score

            # Realistic Dynamic Targets (Based on Next Liquidity/Swing or POC)
            if trade_bias == "BUY":
                sl_price = best_ob['bottom'] * 0.998 if best_ob else (active_sweep['price'] * 0.998 if active_sweep else last_price * 0.99)
                next_swing = next((h[1] for h in reversed(swings_h) if h[1] > last_price), last_price * 1.02)
                tgt_price = max(next_swing, poc) if poc > last_price else next_swing
            else:
                sl_price = best_ob['top'] * 1.002 if best_ob else (active_sweep['price'] * 1.002 if active_sweep else last_price * 1.01)
                next_swing = next((l[1] for l in reversed(swings_l) if l[1] < last_price), last_price * 0.98)
                tgt_price = min(next_swing, poc) if poc < last_price else next_swing

            risk = abs(last_price - sl_price)
            reward = abs(tgt_price - last_price)
            rr_ratio = reward / (risk + 1e-5)

            if rr_ratio < min_rr_threshold or score < 25: 
                continue

            results.append({
                "Stock": ticker, "Sector": STOCK_METADATA[ticker]["sector"],
                "Bias": "🟩 BUY" if trade_bias == "BUY" else "🟥 SELL",
                "Score": round(score, 1),
                "Last Price": f"₹{last_price:.2f}",
                "POC Level": f"₹{poc:.2f}",
                "Context": "Synced Sweep+OB" if (best_ob and active_sweep) else ("Order Block" if best_ob else "Liquidity Sweep"),
                "Target": f"₹{tgt_price:.2f}", "SL": f"₹{sl_price:.2f}",
                "R:R": f"1:{rr_ratio:.2f}", "News": news_context
            })

        except Exception as e:
            continue

    status_text.empty()
    progress_bar.empty()

    if results:
        res_df = pd.DataFrame(results).sort_values(by="Score", ascending=False).reset_index(drop=True)
        st.session_state["scan_results"] = res_df
        st.success(f"✅ Found {len(res_df)} Highly Synchronized Setups out of {len(tickers)} scanned.")
    else:
        st.warning("No setups met the strict synchronization criteria currently.")

# --- 7. VISUALIZER ---
if "scan_results" in st.session_state and not st.session_state["scan_results"].empty:
    res_df = st.session_state["scan_results"]
    
    st.subheader("🎯 Top Synchronized Institutional Setups")
    st.dataframe(res_df, use_container_width=True)
    
    st.subheader("📈 Live Visual Chart (Rank #1 Focus)")
    top_stock = res_df.iloc[0]['Stock']
    
    df_chart, _ = fetch_stock_data(top_stock)
    if not df_chart.empty:
        poc_val = compute_poc(df_chart)
        vwap = (df_chart['Volume'] * (df_chart['High'] + df_chart['Low'] + df_chart['Close']) / 3).cumsum() / df_chart['Volume'].cumsum()
        
        fig = go.Figure(data=[go.Candlestick(
            x=df_chart.index, open=df_chart['Open'], high=df_chart['High'],
            low=df_chart['Low'], close=df_chart['Close'], name="Price"
        )])
        
        fig.add_trace(go.Scatter(x=df_chart.index, y=vwap, line=dict(color='orange', width=1.5), name="VWAP"))
        fig.add_hline(y=poc_val, line_dash="dot", line_color="yellow", annotation_text="Volume POC", annotation_position="top left")
        
        # Plot Dynamic Order Blocks
        ob_zones, _, _, _, _ = detect_synchronized_smc(df_chart, df_chart)
        for zone in ob_zones:
            color = "rgba(0, 255, 0, 0.2)" if zone['bias'] == 'BUY' else "rgba(255, 0, 0, 0.2)"
            border = "green" if zone['bias'] == 'BUY' else "red"
            
            fig.add_shape(
                type="rect", x0=zone['start_time'], x1=df_chart.index[-1],
                y0=zone['bottom'], y1=zone['top'], fillcolor=color, line=dict(color=border, width=1),
            )
            
        fig.update_layout(title=f"Advanced Context: {top_stock} | POC, VWAP & Validated Order Blocks", xaxis_rangeslider_visible=False, template="plotly_dark", height=600)
        st.plotly_chart(fig, use_container_width=True)
